## docker-compose.yml
version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  features:
    build:
      context: .
      dockerfile: Dockerfile.features
    depends_on:
      - rabbitmq
    volumes:
      - ./logs:/app/logs

  metric:
    build:
      context: .
      dockerfile: Dockerfile.metric
    depends_on:
      - rabbitmq
    volumes:
      - ./logs:/app/logs

  plot:
    build:
      context: .
      dockerfile: Dockerfile.plot
    depends_on:
      - metric
    volumes:
      - ./logs:/app/logs
